### ISSUE TITLE
Unable to parse TS files transmuxed by FFmpeg

### ISSUE THREAD

**Issue by gyk** [sile/mpeg2ts#1]
When running the `parse` example on a TS movie transmuxed by FFmpeg, it fails to read the first TS packet which comes with unknown PID 0x11. It might be related to DVB's Service Description Table (SDT).

### Steps to reproduce

1. Download [BigBuckBunny_320x180.mp4](https://download.blender.org/peach/bigbuckbunny_movies/BigBuckBunny_320x180.mp4).

2. Transmux it into TS format:
    ```bash
    ffmpeg -i BigBuckBunny_320x180.mp4 -t 20 -c copy -bsf:v h264_mp4toannexb bbb.ts
    ```

3. Run the `parse` example:
    ```bash
    cat bbb.ts | cargo run --example parse
    ```

    `mpeg2ts` will fail with the following output:

    ```
    thread 'main' panicked at '
    EXPRESSION: reader.read_ts_packet()
    ERROR: InvalidInput (cause; assertion failed: `self.pids.get(&pid).cloned().is_some()`; Unknown PID: header=TsHeader { transport_error_indicator: false, transport_priority: false, pid: Pid(17), transport_scrambling_control: NotScrambled, continuity_counter: ContinuityCounter(0) })
    HISTORY:
    [0] at src/ts/reader.rs:73
    [1] at examples/parse.rs:32

    ', examples/parse.rs:32:38
    ```

**Comment by sile** [comment]
Thanks for reporting this problem. 
Although it is not a complete solution, I fixed `TsPacketReader` so as not to cause an error even if it encounters a packet that has PID 0x11 (commit: https://github.com/sile/mpeg2ts/commit/68e72454506018b4fe3e35884c5660da53ad4ab0 ).

**Comment by gyk** [comment]
Thanks, now it works much better with FFmpeg.
