### ISSUE TITLE
Feature request: implement the .ts file for Apple LL-HLS

### ISSUE THREAD

**Issue by 9to1url** [sile/mpeg2ts#2]
For the new Apple Low latency HLS, requires the .ts file(Partial segment file) should be around 200ms.
Could you advise how to implement this? Or just implement it  :-)

I am using Javelin that using mpeg2ts in Rust.

**Comment by sile** [comment]
Thank you for reaching out.
But, unfortunately, it's hard to give you detailed advice as I'm busy for a while.
You may be able to look at existing rust codes that use this crate such as [scanlime/rectangle-device](https://github.com/scanlime/rectangle-device) (although I don't know the detail of this repo, it seems to limit the max segment length [here](https://github.com/scanlime/rectangle-device/blob/5d4ab6d23b2e295d34e5bcf0a65b824bf17959be/media/src/ingest.rs#L196)).
