### ISSUE TITLE
Insert a stream

### ISSUE THREAD

**Issue by ramyak-mehra** [sile/mpeg2ts#4]
Hey, thanks for the package I was able to parse the stream, is there a way I can insert a new stream to file. My use case is to insert a timed_metadataID3 stream inside the file. 
Thanks

**Comment by sile** [comment]
Hi, thank for using this crate.
Unfortunately, there is no easy way to insert a new stream. You need to build [TsPacket](https://docs.rs/mpeg2ts/latest/mpeg2ts/ts/struct.TsPacket.html)s from the stream and interleave those packets with the existing ones on your own.

**Comment by ramyak-mehra** [comment]
ook ill look into it. Thank you
